name: Build and push image containers

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  WEB_SERVER_IMAGE_NAME: bid098/web-server:latest
  RANDOM_GENERATOR_IMAGE_NAME: bid098/random-generator:latest
  RECIEVER_IMAGE_NAME: bid098/reciever:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.TOKEN }} | docker login ghcr.io -u Bid098 --password-stdin
        - name: Build and Publish Web server Image Container
          run: |
            docker build ./web-server/ --tag ${{ env.REGISTRY }}/${{ env.WEB_SERVER_IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.WEB_SERVER_IMAGE_NAME }}
        - name: Build and Publish Random Generator Image Container
          run: |
            docker build ./random-generator/ --tag ${{ env.REGISTRY }}/${{ env.RANDOM_GENERATOR_IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.RANDOM_GENERATOR_IMAGE_NAME }}
        - name: Build and Publish Reciever Image Container
          run: |
            docker build ./random-generator/ --tag ${{ env.REGISTRY }}/${{ env.RECIEVER_IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.RECIEVER_IMAGE_NAME }}
    
