name: Build and Push Web Server

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bid098/web-server:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.TOKEN }} | docker login ghcr.io -u Bid098 --password-stdin
        - name: Build and Publish
          run: |
            docker build ./web-server/ --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
